framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://localhost
        pools:
            doctrine.second_level_cache_pool:
                adapter: cache.app
                default_lifetime: 3600
