version: '3'

services:
  film_database:
    image: postgres:13.6-alpine3.15
    environment:
      POSTGRES_DB: filmdb
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: development
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  cache:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  db-data:
  cache:
